client:
  extraEnv:
    APP_LOGO: "./logo.svg"
    API_ASSETS_ROUTE: /static-resource
    API_ASSETS_ACTION: assets
    API_MEDIA_ROUTE: /media
    API_MEDIA_SEARCH_ROUTE: "-search"
    API_META_ROUTE: /meta
    API_PROJECTS_ROUTE: /project
    API_RESOLVE_MEDIA_ROUTE: /resolve-media
    API_PROJECT_PUBLISH_ACTION: /publish-project
    API_SCENES_ROUTE: /collection
    API_SERVER_ADDRESS: api-local.etherealengine.com
    API_SOCKET_ENDPOINT: /socket
    API_SERVER: https://api-local.etherealengine.com
    APP_TITLE: EtherealEngine
    CLIENT_ADDRESS: https://local.etherealengine.com
    CLIENT_ENABLED: "true"
    CLIENT_SCENE_ROUTE: /scenes/
    CLIENT_LOCAL_SCENE_ROUTE: "/scene.html?scene_id="
    CORS_PROXY_SERVER: https://api-local.etherealengine.com
    HOST_IP: https://api-local.etherealengine.com
    HOST_PORT: "3000"
    GITHUB_ORG: xr3ngine
    GITHUB_REPO: spoke
    IS_MOZ: "false"
    NEXT_PUBLIC_API_SERVER: https://api-local.etherealengine.com
    NODE_ENV: production
    NON_CORS_PROXY_DOMAINS: "reticulum.io,etherealengine.com,amazonaws.com"
    ROUTER_BASE_PATH: /spoke
    SERVER_ENABLED: "true"
    SITE_DESC: Connected Worlds for Everyone
    SITE_TITLE: XR3ngine
    THUMBNAIL_ROUTE: /thumbnail/
    THUMBNAIL_SERVER: https://api-local.etherealengine.com
    USE_DIRECT_UPLOAD_API: "true"
    USE_HTTPS: "true"
    VITE_APP_HOST: local.etherealengine.com
    VITE_APP_PORT: "3000"
    VITE_SERVER_HOST: api-local.etherealengine.com
    VITE_SERVER_PORT: "3030"
    VITE_INSTANCESERVER_HOST: instanceserver-local.etherealengine.com
    VITE_INSTANCESERVER_PORT: "3031"
  image:
    repository: xrengine
    pullPolicy: IfNotPresent
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
      - host: local.etherealengine.com
        paths:
          - /
  service:
    type: NodePort
domain: etherealengine.com
sql:
  database: xrengine
  password: password
  user: server
  host: host.minikube.internal
  port: 3304
rts:
  extraEnv:
    NAF_LISTEN_PORT: "8081"
api:
  config:
    aws:
      keys:
        access_key_id: <S3_USER_ACCESS_KEY>
        secret_access_key: <S3_USER_SECRET_KEY>
      s3:
        region: us-east-1
        static_resource_bucket: xrengine-static-resources
      cloudfront:
        domain: resources.etherealengine.com
      sns:
        access_key_id: <SNS_USER_ACCESS_KEY>
        application_id: <SNS_APPLICATION_ID>
        region: <SNS_REGION>
        secret_access_key: <SNS_USER_SECRET_KEY>
        sender_id: <SNS_SENDER_ID>
    host: https://local.etherealengine.com/
  extraEnv:
    APP_HOST: local.etherealengine.com
    APP_URL: https://local.etherealengine.com
    AUTH_SECRET: <AUTH_SECRET_UUID_OR_SIMILAR>
    AWS_SMS_ACCESS_KEY_ID: <SNS_USER_ACCESS_KEY>
    AWS_SMS_REGION: <SNS_REGION>
    AWS_SMS_SECRET_ACCESS_KEY: <SNS_USER_SECRET_KEY>
    AWS_SMS_TOPIC_ARN: arn:aws:sns:<SNS_REGION>:<AWS_ACCOUNT_ID>:<SNS_TOPIC_NAME>
    CLIENT_ENABLED: "false"
    CERT: certs/cert.pem
    KEY: certs/key.pem
    CORS_SERVER_PORT: "3036"
    FACEBOOK_CALLBACK_URL: https://local.etherealengine.com/auth/oauth/facebook
    FACEBOOK_CLIENT_ID: "<FACEBOOK_CLIENT_ID>"
    FACEBOOK_CLIENT_SECRET: "<FACEBOOK_CLIENT_SECRET>"
    FORCE_DB_REFRESH: "false"
    INSTANCESERVER_DOMAIN: instanceserver-local.etherealengine.com
    GITHUB_CALLBACK_URL: https://local.etherealengine.com/auth/oauth/github
    GITHUB_CLIENT_ID: "<GITHUB_CLIENT_ID>"
    GITHUB_CLIENT_SECRET: "<GITHUB_CLIENT_SECRET>"
    GOOGLE_CALLBACK_URL: https://local.etherealengine.com/auth/oauth/google
    GOOGLE_CLIENT_ID: "<GOOGLE_CLIENT_ID>"
    GOOGLE_CLIENT_SECRET: "<GOOGLE_CLIENT_SECRET>"
    LOCAL: "false"
    MAGICLINK_EMAIL_SUBJECT: Login to XR3ngine
    MAIL_FROM: info@login.etherealengine.com
    SERVE_CLIENT_FROM_STORAGE_PROVIDER: "true"
    SEVER_ENABLED: "true"
    SERVER_HOST: "api-local.etherealengine.com"
    SERVER_PORT: "3030"
    SMTP_FROM_EMAIL: info@login.etherealengine.com
    SMTP_FROM_NAME: noreply
    SMTP_HOST: email-smtp.<SMTP_REGION>.amazonaws.com
    SMTP_PASS: <SMTP_PASSWORD>
    SMTP_PORT: "465"
    SMTP_SECURE: "true"
    SMTP_USER: <SMTP_USER_ID>
    STORAGE_PROVIDER: local
    LOCAL_STORAGE_PROVIDER: "localhost:8642"
    LOCAL_STORAGE_PROVIDER_PORT: "8642"
    STORAGE_AWS_ACCESS_KEY_ID: <S3_USER_ACCESS_KEY>
    STORAGE_AWS_ACCESS_KEY_SECRET: <S3_USER_SECRET_KEY>
    STORAGE_CLOUDFRONT_DOMAIN: resources.etherealengine.com
    STORAGE_S3_REGION: <S3_REGION>
    STORAGE_S3_STATIC_RESOURCE_BUCKET: xrengine-static-resources
    VITE_APP_HOST: local.etherealengine.com
    VITE_APP_PORT: "3000"
    VITE_SERVER_HOST: api-local.etherealengine.com
    VITE_SERVER_PORT: "3030"
    VITE_INSTANCESERVER_HOST: instanceserver-local.etherealengine.com
    VITE_INSTANCESERVER_PORT: "3031"
    USE_IPFS: "true"
  image:
    repository: xrengine
    pullPolicy: IfNotPresent
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/enable-cors: "false"
#      nginx.ingress.kubernetes.io/cors-allow-origin: https://local.etherealengine.com
      nginx.ingress.kubernetes.io/proxy-body-size: 256m
      nginx.ingress.kubernetes.io/affinity: cookie
      nginx.ingress.kubernetes.io/affinity-mode: persistent
      nginx.ingress.kubernetes.io/server-snippet: |
        location ~* /cors-proxy/(.*) {
          proxy_http_version 1.1;
          proxy_pass_request_headers on;
          proxy_hide_header Access-Control-Allow-Origin;
          proxy_ssl_session_reuse off;
          add_header Initial-Reverse "first";
          proxy_ssl_server_name on;
          add_header Access-Control-Allow-Origin $http_origin;
          proxy_intercept_errors on;
          error_page 301 302 307 = @handle_redirects;
          proxy_pass https://$1?$args;
        }

        location @handle_redirects {
          set $saved_redirect_location '$upstream_http_location';
          proxy_pass_request_headers on;
          add_header Redirect-Reverse "second";
          proxy_hide_header Access-Control-Allow-Origin;
          add_header Access-Control-Allow-Origin $http_origin;
          proxy_pass $saved_redirect_location;
        }
    hosts:
      - host: api-local.etherealengine.com
        paths:
          - /

  service:
    type: NodePort
    corsServerPort: 3036
  replicaCount: 1

media:
  enabled: false
  config:
    aws:
      keys:
        access_key_id: <S3_USER_ACCESS_KEY>
        secret_access_key: <S3_USER_SECRET_KEY>
      s3:
        region: us-east-1
        static_resource_bucket: xr3ngine-static-resources
      cloudfront:
        domain: resources.etherealengine.com
      sns:
        access_key_id: <SNS_USER_ACCESS_KEY>
        application_id: <SNS_APPLICATION_ID>
        region: <SNS_REGION>
        secret_access_key: <SNS_USER_SECRET_KEY>
        sender_id: <SNS_SENDER_ID>
    host: https://local.etherealengine.com/
  extraEnv:
    APP_HOST: local.etherealengine.com
    APP_URL: https://local.etherealengine.com
    AUTH_SECRET: <AUTH_SECRET_UUID_OR_SIMILAR>
    AWS_SMS_ACCESS_KEY_ID: <SNS_USER_ACCESS_KEY>
    AWS_SMS_REGION: <SNS_REGION>
    AWS_SMS_SECRET_ACCESS_KEY: <SNS_USER_SECRET_KEY>
    AWS_SMS_TOPIC_ARN: arn:aws:sns:<SNS_REGION>:<AWS_ACCOUNT_ID>:<SNS_TOPIC_NAME>
    FACEBOOK_CALLBACK_URL: https://local.etherealengine.com/auth/oauth/facebook
    FACEBOOK_CLIENT_ID: "<FACEBOOK_CLIENT_ID>"
    FACEBOOK_CLIENT_SECRET: "<FACEBOOK_CLIENT_SECRET>"
    FORCE_DB_REFRESH: "false"
    GITHUB_CALLBACK_URL: https://local.etherealengine.com/auth/oauth/github
    GITHUB_CLIENT_ID: "<GITHUB_CLIENT_ID>"
    GITHUB_CLIENT_SECRET: "<GITHUB_CLIENT_SECRET>"
    GOOGLE_CALLBACK_URL: https://local.etherealengine.com/auth/oauth/google
    GOOGLE_CLIENT_ID: "<GOOGLE_CLIENT_ID>"
    GOOGLE_CLIENT_SECRET: "<GOOGLE_CLIENT_SECRET>"
    MAGICLINK_EMAIL_SUBJECT: Login to XR3ngine
    MAIL_FROM: info@login.etherealengine.com
    SERVER_ENABLED: "true"
    SERVER_HOST: "api-local.etherealengine.com"
    SMTP_FROM_EMAIL: info@login.etherealengine.com
    SMTP_FROM_NAME: noreply
    SMTP_HOST: email-smtp.<SMTP_REGION>.amazonaws.com
    SMTP_PASS: <SMTP_PASSWORD>
    SMTP_PORT: "465"
    SMTP_SECURE: "true"
    SMTP_USER: <SMTP_USER_ID>
    STORAGE_PROVIDER: local
    LOCAL_STORAGE_PROVIDER: "localhost:8642"
    STORAGE_AWS_ACCESS_KEY_ID: <S3_USER_ACCESS_KEY>
    STORAGE_AWS_ACCESS_KEY_SECRET: <S3_USER_SECRET_KEY>
    STORAGE_CLOUDFRONT_DOMAIN: resources.etherealengine.com
    STORAGE_S3_REGION: <S3_REGION>
    STORAGE_S3_STATIC_RESOURCE_BUCKET: xrengine-static-resources
  image:
    repository: xrengine
    pullPolicy: IfNotPresent
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-origin: https://local.etherealengine.com
      nginx.ingress.kubernetes.io/proxy-body-size: 5m
      nginx.ingress.kubernetes.io/affinity: cookie
      nginx.ingress.kubernetes.io/affinity-mode: persistent
    hosts:
      - host: api-local.etherealengine.com
        paths:
          - /video
  service:
    type: NodePort

release:
  name: "local"

instanceserver:
  image:
    repository: xrengine
    pullPolicy: IfNotPresent
  extraEnv:
    APP_HOST: local.etherealengine.com
    AUTH_SECRET: <AUTH_SECRET_UUID_OR_SIMILAR>
    APP_URL: https://local.etherealengine.com
    CERT: certs/cert.pem
    KEY: certs/key.pem
    INSTANCESERVER_ENABLED: "true"
    INSTANCESERVER_PORT: "3031"
    ROUTE53_ACCESS_KEY_ID: <ROUTE53_USER_ACCESS_KEY>
    ROUTE53_ACCESS_KEY_SECRET: <ROUTE53_USER_SECRET_KEY>
    ROUTE53_HOSTED_ZONE_ID: <ROUTE53_HOSTED_ZONE_ID>
    RTC_START_PORT: "40000"
    RTC_END_PORT: "40099"
    RTC_PORT_BLOCK_SIZE: "100"
    LOCAL: "false"
    INSTANCESERVER_DOMAIN: instanceserver-local.etherealengine.com
    INSTANCESERVER_MODE: "realtime"
    STORAGE_PROVIDER: local
    LOCAL_STORAGE_PROVIDER: "localhost:8642"
    LOCAL_STORAGE_PROVIDER_PORT: "8642"
    NODE_TLS_REJECT_UNAUTHORIZED: "0"
    STORAGE_AWS_ACCESS_KEY_ID: <S3_USER_ACCESS_KEY>
    STORAGE_AWS_ACCESS_KEY_SECRET: <S3_USER_SECRET_KEY>
    STORAGE_CLOUDFRONT_DOMAIN: resources.etherealengine.com
    STORAGE_S3_REGION: <S3_REGION>
    STORAGE_S3_STATIC_RESOURCE_BUCKET: xrengine-static-resources
    TS_NODE_IGNORE: (?:^|\/)node_modules\/(?!(@xrengine))
  ingress:
    disabled: false
    host: instanceserver-local.etherealengine.com
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/enable-cors: "false"
      nginx.ingress.kubernetes.io/proxy-body-size: 256m
      nginx.ingress.kubernetes.io/affinity: cookie
      nginx.ingress.kubernetes.io/affinity-mode: persistent
      nginx.ingress.kubernetes.io/server-snippet: |
        location ~* /primus?$ {
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";
          proxy_pass http://$arg_address:$arg_port/primus?$args;
        }
  buffer:
    bufferSize: 4
    minReplicas: 4
    maxReplicas: 10
    
testbot:
  extraEnv:
    APP_HOST: local.etherealengine.com
  image:
    repository: xrengine-testbot
    pullPolicy: IfNotPresent