{{- if (.Values.taskserver).enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "xrengine.taskserver.fullname" . }}
  labels:
    {{- include "xrengine.taskserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.taskserver.service.type }}
  ports:
    - port: {{ .Values.taskserver.service.port }}
      targetPort: {{ .Values.taskserver.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "xrengine.taskserver.selectorLabels" . | nindent 4 }}
{{- end -}}
