{{- if and (.Values.taskserver).enabled ((.Values.taskserver).serviceAccount).create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "xrengine.taskserver.serviceAccountName" . }}
  labels:
    {{- include "xrengine.taskserver.labels" . | nindent 4 }}
  {{- with .Values.taskserver.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
